### ISSUE TITLE
Cocoapods 版本setup后仍是3.4.5, Installing JPush 3.3.6 (was 3.3.4 and source changed to `https://cdn.cocoapods.org/` from `trunk`), 在trunk更新一下呗

### ISSUE THREAD

**Issue by NiuYangYang** [banchichen/TZImagePickerController#1419] opened 2020-11-10 02:27 UTC
![image](https://user-images.githubusercontent.com/19486884/98619890-18bec780-233f-11eb-9db2-f0c7542615ec.png)

**Comment by banchichen** [comment] 2020-11-10 06:50
Duplicate of #1418

**Closed by banchichen** 2020-11-10 06:50 UTC
